### ISSUE TITLE
Support for nested objects ?

### ISSUE THREAD

**Issue by stefan694** [okonet/yaml-loader#18]
Hi,
I would like to convert a yaml file to json with nested objects but the json isnt nested. 

``` yml
# translations.yml
fr: 
  hello: 'Bonjour'
```

``` js
//main.js
import translations from "json-loader!yaml-loader!./../resources/translations.yml"
console.log(translations)
```

output is `{ fr: null, hello: "Bonjour" }` but it should be :  `{ fr: { hello: "Bonjour" }  }`
